### ISSUE TITLE
FileLoadException on running Demo

### ISSUE THREAD

**Issue by TioLuiso** [VladimirRybalko/CSharpMongoMigrations#8]
Good morning

We are assessing libraries for MongoDb migrations, and yours look promising.

So I cloned it, and opened it on Visual Studio. Try to run the Demo, and there is an exception:

System.IO.FileLoadException
  HResult=0x80131047
  Message=The given assembly name or codebase was invalid. (Exception from HRESULT: 0x80131047)
  Source=System.Private.CoreLib
  StackTrace:
   at System.Reflection.AssemblyName.nInit(RuntimeAssembly& assembly, Boolean forIntrospection, Boolean raiseResolveEvent)
   at System.Reflection.AssemblyName..ctor(String assemblyName)
   at CSharpMongoMigrations.MigrationLocator..ctor(String assemblyName, IMongoDatabase database) in D:\thirdparty\CSharpMongoMigrations\src\CSharpMongoMigrations\MigrationLocator.cs:line 30
   at CSharpMongoMigrations.MigrationRunner..ctor(MongoUrl url, String migrationAssembly) in D:\thirdparty\CSharpMongoMigrations\src\CSharpMongoMigrations\MigrationRunner.cs:line 25
   at CSharpMongoMigrations.MigrationRunner..ctor(String connectionString, String migrationAssembly) in D:\thirdparty\CSharpMongoMigrations\src\CSharpMongoMigrations\MigrationRunner.cs:line 36
   at CSharpMongoMigrations.Demo.Runner.Main(String[] args) in D:\thirdparty\CSharpMongoMigrations\src\CSharpMongoMigrations.Demo\Runner.cs:line 

Am I missing something?

**Comment by TioLuiso** [comment]
Investigating a little, looks like commit a6a945b8 changed

`_assembly = Assembly.LoadFrom(assemblyName);`

with

`_assembly = Assembly.Load(new AssemblyName(assemblyName));`

Assembly.LoadFrom isn't compatible with netstandard 1.6, but it doesn't look like the new version should work

**Comment by TioLuiso** [comment]
Investigation - Part II:

It works if we change

`var runner = new MigrationRunner("mongodb://localhost:27017/TestMigrations", Assembly.GetExecutingAssembly().CodeBase);`

with

`var runner = new MigrationRunner("mongodb://localhost:27017/TestMigrations", Assembly.GetExecutingAssembly().FullName);`

That is, if we pass a path to an assembly (what CodeBase returns), the constructor of AssemblyName explodes. It really expects an assembly name.

Should I fix it?

**Comment by VladimirRybalko** [comment]
Hello @TioLuiso 
Thank you for so detailed investigation.
Of course, you can fix it. Could you please create a new PR with your changes and I'll merge it up with pleasure.
Thank you again.

**Comment by VladimirRybalko** [comment]
It's fixed
